name: Build and Test .NET API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Compilar
      run: dotnet build --configuration Release --no-restore

    - name: Ejecutar tests (si tienes)
      run: dotnet test --no-build --verbosity normal
